**numpy**

contains python objects:- high level number objects and containers like lists and dictionaries

**numpy provides**
extension package to python for multi-dimensional arrays
closer to hardware (efficincy)
designed for scintific computations
also **known as array oriented computing**

In [16]:
import numpy as np
a=np.array([0,1,2,3,4])
print(a)
print(a.ndim) #prints dimensions of array
print(a.shape) # prints shape i.e number of elements
print(len(a))

[0 1 2 3 4]
1
(5,)
5


In [17]:
b=np.array([[1,2,3],[4,5,6]])
print(b)
print(b.ndim)
print(b.shape)
print(len(b))

[[1 2 3]
 [4 5 6]]
2
(2, 3)
2


In [18]:
c=np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
print(c)
print(c.ndim)
print(c.shape)

# n dimentional array is called tensor

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
3
(2, 2, 2)


In [19]:
print(np.arange(10))
print(np.arange(1,10,2))

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [20]:
a=np.linspace(0,1,6) # linear space
print(a)

[0.  0.2 0.4 0.6 0.8 1. ]


In [21]:
a=np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [22]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [23]:
# identity matrix
a=np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
# create arrya using  diag function
a=np.diag([1,2,3,4,5])
print(a)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [28]:
# random numbers
a=np.random.rand(4) # uniformly distributed random numbers
print(a)

b=np.random.randn(4) # normally distributed random numbers
print(b)

[0.13990075 0.08390469 0.09780247 0.03145426]
[ 2.11961473  0.18734463 -0.60269759  0.89298184]


In [34]:
# basic datatypes
a=np.arange(10)
print(a.dtype)

b=np.arange(10,dtype='float64')
print(b)
print(b.dtype)

c=np.array([1+2j,3+4j])
print(c)
print(c.dtype)

d=np.array(['a','b','c'])
print(d)
print(d.dtype)

e=np.array([True,False,True])
print(e)
print(e.dtype)

f=np.array(["ab","bc","ca"])
print(f)
print(f.dtype)

int64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
float64
[1.+2.j 3.+4.j]
complex128
['a' 'b' 'c']
<U1
[ True False  True]
bool
['ab' 'bc' 'ca']
<U2


In [35]:
# slicing
a=np.arange(10)
print(a[5:])
print(a[1:8:2])
print(a[::-1])

[5 6 7 8 9]
[1 3 5 7]
[9 8 7 6 5 4 3 2 1 0]


In [37]:
# copies and views
a=np.arange(10)
b=a[::2]
print(np.shares_memory(a,b))
b[0]=10
print(b)
print(a)

c=a[::2].copy()
print(np.shares_memory(a,c))
c[0]=10
print(c)
print(a)

True
[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]
False
[10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9]


In [40]:
# elementwise operations

a=np.array([1,2,3,4])
print(a+1) # scaler addition
print(a**2)

b=np.ones(4)+1

print(a-b)
print(a*b)
print(a/b)

[2 3 4 5]
[ 1  4  9 16]
[-1.  0.  1.  2.]
[2. 4. 6. 8.]
[0.5 1.  1.5 2. ]


In [41]:
c=np.diag([1,2,3,4,5])

print(c*c)
print("******************")
print(c.dot(c))

[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
******************
[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]


In [43]:
# comparison
a=np.array([1,2,3,4,5])
b=np.array([5,2,3,1,4])
print(a==b)
print(a>b)
print(np.array_equal(a,b))

[False  True  True False False]
[False False False  True  True]
False


In [44]:
# we can perform logical or & and operations using numpy

a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)

print(np.logical_or(a,b))

[ True  True  True False]


In [45]:
a=np.array([1,2,3,4,5])
print(np.sin(a))
print(np.log(a))
print(np.exp(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [47]:
# row and column wise sum
x=np.array([[1,2],[3,4]])
print(x)
print(x.sum(axis=0)) # column wise sum
print(x.sum(axis=1)) # row wise sum

[[1 2]
 [3 4]]
[4 6]
[3 7]


In [50]:
# logical operations
a=np.array([1,1,0,0],dtype=bool)
b=np.array([1,0,1,0],dtype=bool)
print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_not(a))

# logical all and any
print(np.all([True,True,False]))
print(np.any([True,True,False]))

c=np.zeros((50,50))
print(np.any(c!=0))
print(np.all(c==c))

print((a<=b)&(b<=a).all())

[ True False False False]
[ True  True  True False]
[False False  True  True]
False
True
False
True
[False False False False]


In [51]:
# statistics
x=np.array([1,2,3,1])
y=np.array([[1,2,3],[5,6,1]])
print(x.mean())
print(np.median(x))
print(np.median(y,axis=-1)) # last axis
print(x.std())

1.75
1.5
[2. 5.]
0.82915619758885


In [53]:
data = np.loadtxt("population.txt")
print(data)

[[ 1900. 30000.  4000. 48300.]
 [ 1901. 47200.  6100. 48200.]
 [ 1902. 70200.  9800. 41500.]
 [ 1903. 77400. 35200. 38200.]
 [ 1904. 36300. 59400. 40600.]
 [ 1905. 20600. 41700. 39800.]
 [ 1906. 18100. 19000. 38600.]
 [ 1907. 21400. 13000. 38200.]
 [ 1908. 22000.  8300. 39000.]
 [ 1909. 25400.  9100. 44500.]
 [ 1910. 27100.  7400. 42100.]
 [ 1911. 40300.  8000. 46000.]
 [ 1912. 57000. 12300. 46800.]
 [ 1913. 76600. 19500. 43800.]
 [ 1914. 52300. 45700. 40900.]
 [ 1915. 19500. 51100. 39400.]
 [ 1916. 11200. 29700. 40300.]
 [ 1917.  7600. 15800. 42600.]
 [ 1918. 14600.  9700. 42300.]
 [ 1919. 16200. 10500. 41300.]
 [ 1920. 24700.  8600. 47300.]]


In [54]:
year,hares,lynxes,carrots=data.T
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [57]:
populations = data[:,1:] # this will print data from column 1
print(population)

[[30000.  4000. 48300.]
 [47200.  6100. 48200.]
 [70200.  9800. 41500.]
 [77400. 35200. 38200.]
 [36300. 59400. 40600.]
 [20600. 41700. 39800.]
 [18100. 19000. 38600.]
 [21400. 13000. 38200.]
 [22000.  8300. 39000.]
 [25400.  9100. 44500.]
 [27100.  7400. 42100.]
 [40300.  8000. 46000.]
 [57000. 12300. 46800.]
 [76600. 19500. 43800.]
 [52300. 45700. 40900.]
 [19500. 51100. 39400.]
 [11200. 29700. 40300.]
 [ 7600. 15800. 42600.]
 [14600.  9700. 42300.]
 [16200. 10500. 41300.]
 [24700.  8600. 47300.]]


In [58]:
# sample standard deviation
populations.std(axis=0) # this means it is calcluated column wise

array([20897.90645809, 16243.014197  ,  3238.3613336 ])

In [59]:
np.argmax(populations,axis=1) # highest values in each row

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

In [60]:
# broadcasting in numpy

a = np.tile(np.arange(0,40,10),(3,1))
print(a)
print("******************")
print(a.shape)
print("******************")
a=a.T
print(a)

# The given code uses NumPy to create and manipulate a 2D array. First, `np.arange(0, 40, 10)` generates a 1D array `[0, 10, 20, 30]`,
# which consists of values starting from 0 up to (but not including) 40 in steps of 10. This array is then replicated using
#`np.tile(..., (3, 1))`, which stacks the same row three times vertically to form a
# 3x4 matrix: `[[0, 10, 20, 30], [0, 10, 20, 30], [0, 10, 20, 30]]`. The shape of this array is printed as `(3, 4)`,
# meaning it has 3 rows and 4 columns. Then, the `.T` operation transposes the matrix, swapping rows with columns. As a result,
#the transposed matrix becomes `[[0, 0, 0], [10, 10, 10], [20, 20, 20], [30, 30, 30]]`, changing its shape to `(4, 3)`.
#This demonstrates how array tiling and transposing can be used to restructure data layouts effectively using NumPy.

[[ 0 10 20 30]
 [ 0 10 20 30]
 [ 0 10 20 30]]
******************
(3, 4)
******************
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]


In [61]:
# adding a new axix i.e converting it to a 2D array
a = a[:,np.newaxis]
a.shape

(4, 1, 3)

In [62]:
a

array([[[ 0,  0,  0]],

       [[10, 10, 10]],

       [[20, 20, 20]],

       [[30, 30, 30]]])

In [63]:
# arrya manupulations
a = np.array([[1,2,3],[4,5,6]])
print(a.ravel()) # returns a flatterned array

[1 2 3 4 5 6]


In [65]:
print(a.T.ravel())

[1 4 2 5 3 6]


In [66]:
# reshaping
print(a.shape)
print(a)

(2, 3)
[[1 2 3]
 [4 5 6]]


In [67]:
b=a.ravel()
print(b)

[1 2 3 4 5 6]


In [69]:
b= b.reshape((2,3)) # reshape will convert the flaterned array to to 2D
b

array([[1, 2, 3],
       [4, 5, 6]])

In [70]:
# dimension shuffling
a = np.arange(4*3*2).reshape(4,3,2)
print(a.shape)

(4, 3, 2)


In [71]:
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [72]:
print(a[0,2,1])

5


In [73]:
# sorting data

# sorting along the axis
a = np.array([[5,4,6],[2,3,2]])
b = np.sort(a,axis=1)
print(b)

[[4 5 6]
 [2 2 3]]


In [76]:
a.sort(axis=1)
print(a)

[[4 5 6]
 [2 2 3]]
